# Generated by Django 5.2.5 on 2025-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_coupon_couponredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('SALE', 'SALE'), ('PAYLATER', 'PAYLATER'), ('RENT', 'RENT')], default='SALE', max_length=100),
        ),
    ]
