# Generated by Django 5.2.5 on 2025-10-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0007_product_status_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='apiv1_locat_name_519e83_idx'), models.Index(fields=['is_active'], name='apiv1_locat_is_acti_cb1eff_idx')],
            },
        ),
    ]
