# Generated by Django 5.2.5 on 2025-11-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0009_product_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('Ahafo', 'Ahafo'), ('Ashanti', 'Ashanti'), ('Bono East', 'Bono East'), ('Brong Ahafo', 'Brong Ahafo'), ('Central', 'Central'), ('Eastern', 'Eastern'), ('Greater Accra', 'Greater Accra'), ('North East', 'North East'), ('Northern', 'Northern'), ('Oti', 'Oti'), ('Savannah', 'Savannah'), ('Upper East', 'Upper East'), ('Upper West', 'Upper West'), ('Volta', 'Volta'), ('Western', 'Western'), ('Western North', 'Western North')], default='Greater Accra', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='duration',
            field=models.CharField(default='One Time Payment', max_length=100),
        ),
    ]
