# Generated by Django 5.2.5 on 2025-11-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0010_location_region_product_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
