# Generated by Django 5.2.5 on 2025-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0014_subscription_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='discountn_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount on the original price if any', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(default='', help_text='Comma-separated list of features included in this subscription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_products',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of products allowed under this subscription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Just a tag to be used for differentiating plans', max_digits=5),
        ),
        migrations.AddField(
            model_name='subscription',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.CharField(default='BASIC', max_length=50),
            preserve_default=False,
        ),
    ]
