# Generated by Django 5.2.5 on 2025-11-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0015_subscription_discountn_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='max_products',
            field=models.PositiveIntegerField(help_text='Maximum number of products allowed under this subscription. Use 0 for unlimited.'),
        ),
    ]
