# Generated by Django 5.2.5 on 2025-11-21 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0016_alter_subscription_max_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('provider', models.CharField(default='paystack', max_length=30)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, help_text='Subscription this payment is intended for (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='apiv1.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='Payment record that funded this subscription (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subscription', to='apiv1.payment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference'], name='apiv1_payme_referen_a990a8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='apiv1_payme_status_844138_idx'),
        ),
    ]
