# Generated by Django 5.2.5 on 2025-11-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0017_payment_usersubscription_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='discountn_percentage',
            new_name='discount_percentage',
        ),
    ]
