# Generated by Django 5.2.5 on 2025-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0018_rename_discountn_percentage_subscription_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED'), ('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
    ]
