# Generated by Django 5.2.5 on 2025-11-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0020_accountdeleterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Privacy Policy', max_length=200)),
                ('date', models.DateField()),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Terms and Conditions', max_length=200)),
                ('date', models.DateField()),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
