# Generated by Django 5.2.5 on 2025-12-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0023_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suspension_note',
            field=models.TextField(blank=True, help_text='Reason provided when this product is suspended by an admin.', null=True),
        ),
    ]
