# Generated by Django 5.2.5 on 2025-12-09 20:52

import apiv1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0025_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_id',
            field=models.CharField(default=apiv1.models.JobApplication.generate_application_id, max_length=20, unique=True),
        ),
    ]
