# Generated by Django 5.2.5 on 2025-12-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0026_alter_jobapplication_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_media',
            field=models.BooleanField(default=False),
        ),
    ]
