# Generated by Django 5.2.5 on 2026-01-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0029_chatroom_is_closed_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
