# Generated by Django 5.2.5 on 2025-09-29 10:35

import accounts.models
import django.db.models.deletion
import oysloecore.sysutils.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[(oysloecore.sysutils.constants.UserLevelTrack['SILVER'], 'SILVER'), (oysloecore.sysutils.constants.UserLevelTrack['GOLD'], 'GOLD'), (oysloecore.sysutils.constants.UserLevelTrack['DIAMOND'], 'DIAMOND')], default='SILVER', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('points', models.IntegerField(choices=[(5, '5'), (50, '50')], default=5)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=accounts.models.Referral.generate_ref_code, max_length=20, unique=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
