# Generated by Django 5.2.5 on 2025-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_level_user_referral_points_coupon_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('SILVER', 'SILVER'), ('GOLD', 'GOLD'), ('DIAMOND', 'DIAMOND')], default='SILVER', max_length=10),
        ),
    ]
