# Generated by Django 5.2.5 on 2025-09-29 18:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='used_referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=accounts.models.User.generate_referral_code, max_length=20, unique=True),
        ),
    ]
