# Generated by Django 5.2.5 on 2025-10-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_otp_email_otp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
