# Generated by Django 5.2.5 on 2025-11-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
