# Generated by Django 5.2.5 on 2025-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(default='*** *** *** ***', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='id_back_page',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_front_page',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='*** *** *** ***', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='second_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
