# Generated by Django 5.2.5 on 2025-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_account_name_user_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
    ]
