# Generated by Django 5.2.5 on 2025-12-18

from django.db import migrations, models


def backfill_user_ad_counts(apps, schema_editor):
    """Best-effort backfill from current Product rows.

    True historical totals (including deleted products) cannot be reconstructed,
    so we initialize the counters to the current counts.
    """
    User = apps.get_model('accounts', 'User')
    try:
        Product = apps.get_model('apiv1', 'Product')
    except LookupError:
        return

    try:
        from django.db.models import Count, Q
    except Exception:
        return

    stats = (
        Product.objects
        .filter(owner_id__isnull=False)
        .values('owner_id')
        .annotate(
            total_ads=Count('id'),
            total_taken_ads=Count('id', filter=Q(is_taken=True)),
        )
    )

    for row in stats:
        User.objects.filter(id=row['owner_id']).update(
            total_ads=row.get('total_ads') or 0,
            total_taken_ads=row.get('total_taken_ads') or 0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_id_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_ads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_taken_ads',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_user_ad_counts, migrations.RunPython.noop),
    ]
