# Generated by Django 5.2.5 on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_persistent_ad_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wrong_coupon_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='can_redeem_coupon',
            field=models.BooleanField(default=True),
        ),
    ]
