# Generated by Django 5.2.5 on 2025-12-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_coupon_redemption_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCashoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('momo_number', models.CharField(max_length=50)),
                ('momo_network', models.CharField(max_length=50)),
                ('momo_account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='cashout_requests', to='accounts.user')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'status'], name='accounts_wcr_user_status_idx'),
                    models.Index(fields=['created_at'], name='accounts_wcr_created_at_idx'),
                ],
            },
        ),
    ]
