# Generated by Django 5.2.5 on 2026-01-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_wallet_cashout_request_provider_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
