# Generated by Django 5.2.7 on 2026-01-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_business_name_alter_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_logo',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_back_page',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_front_page',
            field=models.URLField(blank=True, max_length=800, null=True),
        ),
    ]
