# Generated by Django 5.2.5 on 2025-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
